Two step Form
Sulagna-Dutta-Roy/Webeginner-projects pull request #100
Opened 2022-08-07 17:35 UTC by iamrahul8

# Description

A basic Two-step Form design, made with HTML, CSS and Javascript.

>It pays close attention to the information collected when making a reservation for a flat or building.

Fixes:  #49 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

[Deployment Link](https://iamrahul8.github.io/two-step-form/)

![image](https://user-images.githubusercontent.com/72541381/183303615-45a5cd51-6471-4051-8715-ceeaa40d6449.png)

2022-08-08 02:14 UTC, siddhi-244 requested changes
If there is nothing in the css file you can remove it

2022-08-08 13:22 UTC, iamrahul8 commented
> If there is nothing in the css file you can remove it

Done ✌

2022-08-09 14:03 UTC, Sulagna-Dutta-Roy approved these changes

2022-08-16 17:23 UTC, siddhi-244 approved these changes

2022-08-16 17:35 UTC, merged