init
Sulagna-Dutta-Roy/Webeginner-projects pull request #108
Opened 2022-08-08 11:25 UTC by surajchavan19

initial commit

# Description

The drawing board is a simple whiteboard made using HTML, CSS, and JS that you can use to draw and express your creativity and imagination.
Fixes:  #89 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
<img width="1440" alt="preview" src="https://user-images.githubusercontent.com/38256861/183407349-3319e5f7-19fd-4395-b0e7-f725463e96c9.png">

2022-08-09 14:06 UTC, Sulagna-Dutta-Roy requested changes
whiteboard.css file not showing here.Please check if it's blank then remove it. Also there is Ds store file u can remove it

2022-08-09 16:35 UTC, surajchavan19 commented
I have done the required changes.

2022-08-09 17:23 UTC, Sulagna-Dutta-Roy approved these changes

2022-08-11 19:09 UTC, Sulagna-Dutta-Roy approved these changes

2022-08-17 18:32 UTC, siddhi-244 approved these changes

2022-08-18 19:18 UTC, merged