Landing page with dynamic background
Sulagna-Dutta-Roy/Webeginner-projects pull request #113
Opened 2022-08-08 16:45 UTC by iamrahul8

# Description
I designed a landing page with dynamic background.

>It Depicts a landing page for travel blog

Fixes:  #104 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
[Demo](https://iamrahul8.github.io/Landing-Page/)

![image](https://user-images.githubusercontent.com/72541381/183469845-10003ab7-a9ce-458f-8560-da68e1538914.png)

2022-08-09 14:14 UTC, Sulagna-Dutta-Roy requested changes
Can you please change the headline into 'Landing Page' ? also background.gif file not showing here

2022-08-09 18:31 UTC, iamrahul8 commented
> Can you please change the headline into 'Landing Page' ? also background.gif file not showing here

- File name changes  >Landing Page
- Demo link : https://iamrahul8.github.io/Landing-Page/

>Everything is working fine 👍

2022-08-11 19:03 UTC, Sulagna-Dutta-Roy approved these changes

2022-08-16 17:24 UTC, siddhi-244 approved these changes

2022-08-16 17:33 UTC, merged