User can see number of tries in Number Guessing Game
Sulagna-Dutta-Roy/Webeginner-projects pull request #133
Opened 2022-08-12 13:25 UTC by pritika163

# Description

I have added a feature that lets the user know how many times he/she has tried before guessing the correct number.

Fixes:  #128 

 # Type of change
- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Before:
![Screenshot (702)beforefinal](https://user-images.githubusercontent.com/102177744/184361802-edb80189-391d-4aba-9536-7a5716cfdb28.png)

After:
![Screenshot (701) final](https://user-images.githubusercontent.com/102177744/184361941-25e1b071-1551-44c8-b8b5-0a86422de1a2.png)

2022-08-12 19:57 UTC, Sulagna-Dutta-Roy requested changes
kindly add readme.md file here

2022-08-13 07:43 UTC, Sulagna-Dutta-Roy approved these changes

2022-08-17 13:17 UTC, siddhi-244 approved these changes

2022-08-18 19:12 UTC, Sulagna-Dutta-Roy commented
Where is the readme.file ??

2022-08-18 19:36 UTC, merged