Added Facebook Login Clone code
Sulagna-Dutta-Roy/Webeginner-projects pull request #161
Opened 2022-08-16 09:08 UTC by Rancho2002

# Description

Added the HTML, CSS code of 'Facebook login clone code'. This project is created using Tailwind CSS and npm run build.

Fixes:  #145 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
![clone](https://user-images.githubusercontent.com/92109154/184841256-5ffec6d1-9614-4c58-b4b6-267c912491b9.png)

2022-08-16 12:35 UTC, siddhi-244 requested changes
Add more info in readme and structure it properly

2022-08-17 04:11 UTC, Rancho2002 commented
I have modified readme.md and structured it properly, Please recheck the pull request. @siddhi-244 @Sulagna-Dutta-Roy

2022-08-17 04:11 UTC, Rancho2002 commented
I have modified readme.md and structured it properly, Please recheck the pull request. @siddhi-244 @Sulagna-Dutta-Roy

2022-08-17 09:56 UTC, Sulagna-Dutta-Roy approved these changes

2022-08-17 13:17 UTC, siddhi-244 approved these changes

2022-08-17 20:20 UTC, merged