Random Recipe Generator
Sulagna-Dutta-Roy/Webeginner-projects pull request #190
Opened 2022-08-19 20:41 UTC by surajchavan19

Files added

# Description

This website uses TheMealDB API to fetch the recipe along with the instructions and ingredients required to make the recipe. I have also embedded the youtube video of the recipe to make it easy for the users to follow the recipe.

Technologies Used:
HTML, CSS, JS ,and TheMealDB API

Fixes:  #179 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

Before:

![Screenshot 2022-08-18 at 12 12 58 AM](https://user-images.githubusercontent.com/38256861/185218122-caeeb96d-4af9-4027-bca9-0e978b9bf8de.png)

After:

![Screenshot 2022-08-17 at 11 58 55 PM](https://user-images.githubusercontent.com/38256861/185217887-4745dc52-a7ec-4af8-a640-65fa8a68cfc0.png)
![Screenshot 2022-08-17 at 11 59 10 PM](https://user-images.githubusercontent.com/38256861/185217997-7913c56a-9da7-4cab-87de-3e25ba45ee94.png)
![Screenshot 2022-08-17 at 11 59 18 PM](https://user-images.githubusercontent.com/38256861/185218040-c03cf8da-bad6-4764-be34-4b1d95fdac43.png)

2022-08-22 16:31 UTC, Sulagna-Dutta-Roy requested changes
Please add readme file

2022-08-23 09:11 UTC, surajchavan19 commented
I have added the README file

2022-08-23 09:24 UTC, siddhi-244 requested changes
Add screenshot in readme

2022-08-23 20:25 UTC, Sulagna-Dutta-Roy approved these changes

2022-08-24 01:41 UTC, siddhi-244 approved these changes

2022-08-24 07:05 UTC, merged