Ice_cream website
Sulagna-Dutta-Roy/Webeginner-projects pull request #192
Opened 2022-08-20 05:08 UTC by Cypher1002

# Description

made a full website using taildwind css and html 

Fixes:  #19 

added ice_cream website

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have made this from my own
- [ ] I have taken help from some online resourses 
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

2022-08-23 20:24 UTC, Sulagna-Dutta-Roy requested changes
Please add the readme file here. also tick all the PR template checkboxes.

2022-08-30 19:24 UTC, Sulagna-Dutta-Roy approved these changes

2022-08-31 03:25 UTC, siddhi-244 approved these changes

2022-09-05 18:04 UTC, 072arushi reviewed
Kudos! Great efforts...

2022-09-05 18:04 UTC, 072arushi approved these changes

2022-09-05 20:07 UTC, merged