updated UI and added new features.
Sulagna-Dutta-Roy/Webeginner-projects pull request #204
Opened 2022-08-21 14:14 UTC by MDeexith

# Description

The previous content was not quit enough for good stopwatch website so here I created a stopwatch which is able to some extra tasks. 

Fixes:  #57 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
![Screenshot 2022-08-21 193758](https://user-images.githubusercontent.com/88663554/185795031-e4dbe857-b7b8-4611-a59a-43e9c97c50e6.png)

2022-08-22 00:31 UTC, siddhi-244 approved these changes

2022-08-22 16:27 UTC, Sulagna-Dutta-Roy approved these changes

2022-08-23 01:44 UTC, siddhi-244 requested changes
Add the new ui screenshot in readme

2022-08-23 06:50 UTC, siddhi-244 approved these changes

2022-08-23 20:17 UTC, merged

2022-08-23 20:19 UTC, Sulagna-Dutta-Roy commented
Tell me you are part of ssoc or not @MDeexith