Added Educational website
Sulagna-Dutta-Roy/Webeginner-projects pull request #207
Opened 2022-08-22 06:27 UTC by vedsom

# Description

Added educational website containing different types of data written/videos and courses for required skills.

Fixes:  #199

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
![Bright Minds - Google Chrome 22-07-2022 18_21_16](https://user-images.githubusercontent.com/96954912/185853062-a88f3a6f-51ad-4de2-9fec-ab3abec98515.png)
![Bright Minds - Google Chrome 22-07-2022 18_21_39](https://user-images.githubusercontent.com/96954912/185853096-b1237006-cfa4-4935-9bcc-33de0eef643a.png)
![Bright Minds - Google Chrome 29-05-2022 22_02_11](https://user-images.githubusercontent.com/96954912/185853133-0d248910-32ec-4b2f-a11e-8cb6fd5c75c9.png)
![Bright Minds - Google Chrome 22-07-2022 18_24_43](https://user-images.githubusercontent.com/96954912/185853162-ada91dd9-2c24-4a11-9217-4292f25d95ef.png)

2022-08-22 06:28 UTC, vedsom commented
@Sulagna-Dutta-Roy kindly review the PR!! Thanks!!

2022-08-22 12:16 UTC, Sulagna-Dutta-Roy requested changes
Please add Readme file here.

2022-08-26 15:47 UTC, vedsom commented
> Please add Readme file here.

@Sulagna-Dutta-Roy  I have added the readme file. kindly have a look.

2022-08-27 04:34 UTC, Sulagna-Dutta-Roy approved these changes

2022-08-27 04:47 UTC, siddhi-244 approved these changes

2022-08-27 04:54 UTC, merged