feat: analog clock created
Sulagna-Dutta-Roy/Webeginner-projects pull request #211
Opened 2022-08-22 11:59 UTC by siddharthPriyadarshi

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #(issue no.)

## Type of change

- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ x] I have made this from my own
- [ x] I have taken help from some online resourses 
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
![analog-clock](https://user-images.githubusercontent.com/74820758/185915645-1e48594c-e3ed-4064-b7c8-2c9ed7321be6.png)

2022-08-22 12:14 UTC, Sulagna-Dutta-Roy requested changes
Please add Readme File here. Also tick all the checkboxes in the PR template

2022-08-24 13:43 UTC, siddharthPriyadarshi commented
Readme added
Tick boxes checked
Issue no added

Kindly review it

2022-08-24 17:31 UTC, siddhi-244 approved these changes

2022-08-25 18:47 UTC, Sulagna-Dutta-Roy approved these changes

2022-08-25 18:50 UTC, merged