Updated with additional functionalities
Sulagna-Dutta-Roy/Webeginner-projects pull request #227
Opened 2022-08-24 19:59 UTC by hacker626

# Description

This Rocket games being created out from pygame is being updated to fill-up various flaws.
I have added different functionality as follows:

1. Added GameOver logic when the enemy reach or crosses the player area.
2. Added Paused State
3. Added Exit state.
4. Updated the Readme.md

Fixes:  #221 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
![rocket_1](https://user-images.githubusercontent.com/66233331/186510815-37364859-7601-4a7f-966b-5cdf3b9f65ec.jpg)
![rocket_2](https://user-images.githubusercontent.com/66233331/186510819-3462d193-726e-421f-8e88-d38e7555c101.jpg)

2022-08-25 01:45 UTC, siddhi-244 approved these changes

2022-08-25 16:50 UTC, Sulagna-Dutta-Roy requested changes
Please filename change into Rocket attack game.py

2022-08-25 21:44 UTC, hacker626 commented
Please Check, I have renamed the filename from "main.py" to "Rocket_Attack_Game.py".

2022-08-28 01:39 UTC, Sulagna-Dutta-Roy approved these changes

2022-08-28 01:40 UTC, merged