Snake game
Sulagna-Dutta-Roy/Webeginner-projects pull request #229
Opened 2022-08-25 11:07 UTC by Abbhiishek

# Description 
 
Issue #228 

Snake Game is a simple game where the player controls a snake and must avoid the walls.
It will be a 2d game with a small snake and some random food.

The snake will start off small and will grow in size as it eats the food. The food will be randomly swapped each time it is eaten.

There will be a score system which keeps track of the amount of food the snake has eaten.

The game will end when the snake either collides with the wall or itself.

Fixes:  #228 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
![snake demo](https://user-images.githubusercontent.com/86338762/186648690-0f0b229e-a901-4e65-b2a5-79e31484f6bf.png)

2022-08-25 17:14 UTC, siddhi-244 approved these changes

2022-08-25 17:18 UTC, Sulagna-Dutta-Roy approved these changes

2022-08-25 17:18 UTC, Sulagna-Dutta-Roy requested changes
Add this project into Python file

2022-08-29 10:55 UTC, Sulagna-Dutta-Roy approved these changes

2022-08-29 10:56 UTC, merged