Resume builder Web app added
Sulagna-Dutta-Roy/Webeginner-projects pull request #254
Opened 2022-09-07 13:33 UTC by Rishikavishnoi

Description

It is a resume generator web app that can build your resume by just simply filling the form of information
You can also  print it also in pdf format 
Tech used :- HTML , CSS , JAVASCRIPT ,BOOTSTRAP

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

- [x] My changes generate no new warnings

![ss](https://user-images.githubusercontent.com/84177590/188891393-e2dc1b39-427c-4718-86fd-7efa2703c565.png)
![ss2](https://user-images.githubusercontent.com/84177590/188891407-88ad2a7d-4bfe-44b8-b3c9-f1ef973d25c7.png)

2022-09-07 14:42 UTC, Sulagna-Dutta-Roy requested changes
mention your issue no

2022-09-08 18:15 UTC, siddhi-244 approved these changes

2022-09-08 18:27 UTC, Sulagna-Dutta-Roy commented
Just a suggestion: It will be a great project if you make this project in ReactJs. Add more features and deploy it.

2022-09-08 18:32 UTC, Rishikavishnoi commented
@Sulagna-Dutta-Roy thanks for the suggestion...I'll try to build using Reactjs but as per the rule we can't upload the projects in reactjs so I build in javascript  to contribute in these repository.

2022-09-12 19:01 UTC, 072arushi approved these changes

2022-09-12 19:13 UTC, merged