Added google keep clone project
Sulagna-Dutta-Roy/Webeginner-projects pull request #259
Opened 2022-09-08 14:43 UTC by sshiwangi

# Description

Designed Google keep clone using html and css.
The website is responsive and follows exact color theme as the original website.

Fixes: 

#233 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
![google keep](https://user-images.githubusercontent.com/77545230/189152023-3ed9b01c-10ce-433b-94b1-6cc2cb1c85b1.png)

2022-09-09 18:43 UTC, Sulagna-Dutta-Roy requested changes
please delete the .vscode file

2022-09-11 08:37 UTC, Sulagna-Dutta-Roy approved these changes

2022-09-11 08:51 UTC, siddhi-244 approved these changes

2022-09-12 19:01 UTC, 072arushi approved these changes

2022-09-12 19:15 UTC, merged