Url shortener
Sulagna-Dutta-Roy/Webeginner-projects pull request #270
Opened 2022-09-12 17:09 UTC by prjailani

# Description

Created a URL shortener using Python. Need to install **pyshorteners** package. Run **pip install pyshorteners** to install this dependency.

Fixes:  #268

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
![Screenshot (36)](https://user-images.githubusercontent.com/76675034/189713812-31b03bcc-5411-408d-9414-bb107b157889.png)

2022-09-12 18:54 UTC, 072arushi reviewed
Good but I guess you should add more to your project.

2022-09-13 19:43 UTC, Sulagna-Dutta-Roy approved these changes

2022-09-13 19:44 UTC, Sulagna-Dutta-Roy requested changes
why you pasted PR template in the readme??

2022-09-15 16:50 UTC, prjailani commented
> why you pasted PR template in the readme??

Changed Readme.md file now. Thanks.

2022-09-19 19:52 UTC, Sulagna-Dutta-Roy approved these changes

2022-09-24 20:13 UTC, 072arushi approved these changes

2022-09-25 13:18 UTC, siddhi-244 approved these changes

2022-09-25 19:20 UTC, merged