Flappy Bird clone #256
Sulagna-Dutta-Roy/Webeginner-projects pull request #278
Opened 2022-09-17 13:25 UTC by shwetmala55

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #(issue no.)

## Type of change

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
![flappy_pic2](https://user-images.githubusercontent.com/99597479/190859229-988aff3d-35cf-4ab2-a380-5f1d55be7258.png)

2022-09-18 18:54 UTC, Sulagna-Dutta-Roy approved these changes

2022-09-18 19:00 UTC, 072arushi requested changes
Include the problem statement, technologies used, and the whole description. Update your readme file.

2022-09-20 19:57 UTC, 072arushi approved these changes

2022-09-21 03:07 UTC, siddhi-244 approved these changes

2022-09-21 08:57 UTC, merged