Feat 281 added color game using tkinter in python
Sulagna-Dutta-Roy/Webeginner-projects pull request #287
Opened 2022-09-20 14:44 UTC by SSHSRN

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #281 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
![image](https://user-images.githubusercontent.com/62781914/191289156-ac18686b-f15d-492b-be43-4bd1383906aa.png)

2022-09-21 03:08 UTC, siddhi-244 requested changes
Add more information in the readme.  Check out other prs

2022-09-21 16:35 UTC, Sulagna-Dutta-Roy approved these changes

2022-09-24 20:13 UTC, 072arushi approved these changes

2022-09-25 13:18 UTC, siddhi-244 commented
@SSHSRN any updates on the changes ?

2022-10-01 18:10 UTC, merged