Title:Exploratory data analysis using student dataset
Sulagna-Dutta-Roy/Webeginner-projects pull request #296
Opened 2022-09-22 13:08 UTC by Labheshm11

# Description

This is an eda that makes us understand the basics fundamentals in the Covid-19 datasets

Technologies
python-(pandas,NumPy,matplotlib,Kaggle(dataset)

Fixes:  #288 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [✅] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:
- [✅ ] I have made this on my own
- [ ✅] I have taken help from some online resources 
- [ ✅] My code follows the style guidelines of this project
- [ ✅] I have performed a self-review of my own code
- [✅ ] I have commented on my code, particularly in hard-to-understand areas
- [ ✅] I have made corresponding changes to the documentation
- [ ✅] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
![Screenshot (183)](https://user-images.githubusercontent.com/90571547/191754352-1c5322d2-c161-4e4e-85c3-457b1bf4b3a6.png)
![Screenshot (184)](https://user-images.githubusercontent.com/90571547/191754356-a1c94426-b60e-4231-8e5f-c3ece9e69672.png)
![Screenshot (185)](https://user-images.githubusercontent.com/90571547/191754362-508926c9-490e-47f9-b4f9-0e6fdc794010.png)
![Screenshot (186)](https://user-images.githubusercontent.com/90571547/191754368-03bd66a9-30a8-45da-bd7a-303b885a64ca.png)

2022-09-22 17:25 UTC, Sulagna-Dutta-Roy requested changes
Please update the PR template,write this for the checkbox:  [X]

2022-09-22 18:12 UTC, Labheshm11 commented
@Sulagna-Dutta-Roy 
Changes done

2022-09-23 17:57 UTC, Sulagna-Dutta-Roy approved these changes

2022-09-24 02:31 UTC, siddhi-244 approved these changes

2022-09-24 11:13 UTC, Labheshm11 commented
@072arushi plz review the pr

2022-09-24 12:17 UTC, 072arushi approved these changes

2022-09-25 08:34 UTC, merged