Improved UI of Number Guessing Game
Sulagna-Dutta-Roy/Webeginner-projects pull request #302
Opened 2022-09-23 20:36 UTC by Sanskar50

# Description

Enhanced the UI of the Number Guessing Game by-
- Better color combinations
- Improved fonts
- Improved buttons
- Proper Spacing
- Added Background image

FIXES-#295

## Type of change

- [x] Improved user interface

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### 📷 Screenshots

# OLDER VERSION

![Screenshot (78)](https://user-images.githubusercontent.com/99363431/192051683-45789f11-2b20-4d83-a5e4-bef245830823.png)

# IMPROVED VERSION

![Screenshot (79)](https://user-images.githubusercontent.com/99363431/192051858-0361dab0-ca93-46d4-b861-3ca188755a7a.png)

2022-09-24 02:33 UTC, siddhi-244 requested changes
Can you add screenshot of new ui in the readme

2022-09-24 06:11 UTC, Sanskar50 commented
I have updated the readme file👍
But my previous commit is showing error in workflow- greeting saying "docker build failed" what should I do to resolve this?

2022-09-25 08:56 UTC, Sulagna-Dutta-Roy approved these changes

2022-09-25 13:16 UTC, siddhi-244 approved these changes

2022-09-26 12:29 UTC, 072arushi approved these changes

2022-09-26 16:35 UTC, merged