# 21 Dice-Game Added
Sulagna-Dutta-Roy/Webeginner-projects pull request #83
Opened 2022-08-07 08:59 UTC by vaibhavchaubey

# Description

I have made a Dice-Game web Application. Every time when the user refreshes the page it then shows the result.

Fixes:  #21 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / [DEPLOYMENT LINK](https://vaibhavchaubey.github.io/Dice-Game/)
![Pic_1](https://user-images.githubusercontent.com/88048439/183283112-1b2544d7-4f1e-4130-aa7b-0198eb18a00d.png)

2022-08-07 12:07 UTC, siddhi-244 requested changes
It would be great if you can add more details in the readme

2022-08-07 17:03 UTC, vaibhavchaubey commented
> It would be great if you can add more details in the readme

Done

2022-08-08 02:09 UTC, siddhi-244 approved these changes
LGTM.

2022-08-08 08:50 UTC, Sulagna-Dutta-Roy approved these changes

2022-08-08 08:51 UTC, merged